### ISSUE TITLE
Не работает. 

### ISSUE THREAD

**Issue by alentsov** [AlexSt93/Parking#1]
Как заставить работать это приложение? Хочется инструкцию, пройдя которую, мы получили бы работающее приложение. 

Сейчас в Resources лежат два одинаковых файла на создание одной и той же таблицы, в результате не работает

**Comment by alentsov** [comment]
Всё еще не работает: 
При запуске клиента имеем: 
ant -f C:\Users\alen1013\Documents\UNC\AlexSt\Parking -Djavac.includes=ClientPac/Client.java -Drun.class=ClientPac.Client -Dnb.internal.action.name=run.single run-single
init:
Deleting: C:\Users\alen1013\Documents\UNC\AlexSt\Parking\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\alen1013\Documents\UNC\AlexSt\Parking\build\built-jar.properties
Compiling 1 source file to C:\Users\alen1013\Documents\UNC\AlexSt\Parking\build\classes
compile-single:
run-single:
Exception in Application start method
The server might not be up at this time.
Please try again later.
BUILD SUCCESSFUL (total time: 0 seconds)

На сервере: 
Connected to base
Client Socket[addr=/127.0.0.1,port=51739,localport=8080]connected
java.io.EOFException
    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2325)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2794)
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at ServerPac.ClientThread.run(ClientThread.java:59)

**Comment by alentsov** [comment]
Этой проблемы не наблюдается. 
Решение проблемы: пересоздать таблицы c помощью 
./src/Resources/place.sql
./src/Resources/parking.sql

На остальные проблемы - другие тикеты.
